apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: darpo-dev

bases:
  - ../../base

commonLabels:
  environment: development

resources:
  - namespace.yaml

patches:
  - path: patches/deployment.yaml
  - path: patches/configmap.yaml