apiVersion: apps/v1
kind: Deployment
metadata:
  name: darpo-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: darpo-app
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi