apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: darpo-prod

bases:
  - ../../base

commonLabels:
  environment: production

resources:
  - namespace.yaml

patches:
  - path: patches/deployment.yaml
  - path: patches/configmap.yaml
  - path: patches/hpa.yaml